import { Cabin } from "next/font/google"
import "./globals.css"
import PrelineScript from "@/components/PrelineScript"

const inter = Cabin({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ background: "#ebf3fd" }}>
        {children}
      </body>
      <PrelineScript />
    </html>
  )
}
